[versions]
spring-boot = "3.5.3"

[libraries]
gradle-spring-boot = { module = "org.springframework.boot:spring-boot-gradle-plugin", version.ref = "spring-boot" }
gradle-lombok = { module = "io.freefair.gradle:lombok-plugin", version = "8.11" }
gradle-spotless = { module = "com.diffplug.spotless:spotless-plugin-gradle", version = "7.0.3" }
